version: '3'
services:
 broker-rabbitmq:
   image: "rabbitmq:3.9.13-management"
   ports:
     - "15672:15672"
   environment:
     - RABBITMQ_DEFAULT_USER=rabbit_user
     - RABBITMQ_DEFAULT_PASS=rabbit_password
 db-postgres:
   image: "postgres:11.2"
   environment:
     - POSTGRES_USER=db_user
     - POSTGRES_PASSWORD=db_password
 api:
   build: .
   ports:
    - "8000:8000"
   environment:
     - APP_ENV=Dev
     - GET_HOSTS_FROM=dns
   depends_on:
     - broker-rabbitmq
     - db-postgres
 api-worker01:
   build: .
   ports:
    - "8010:8010"
   command: celery -A tasks.celery worker --loglevel=info
   environment:
     - APP_ENV=Dev
   depends_on:
     - broker-rabbitmq
     - db-postgres
 api-worker02:
   build: .
   ports:
    - "8020:8020"
   command: celery -A tasks.celery worker --loglevel=info
   environment:
     - APP_ENV=Dev
   depends_on:
     - broker-rabbitmq
     - db-postgres
 api-beat:
   build: .
   ports:
    - "8030:8030"
   command: celery -A tasks.celery beat --loglevel=info
   environment:
     - APP_ENV=Dev
   depends_on:
     - broker-rabbitmq
     - db-postgres
 celery-flower:
   image: gregsi/latest-celery-flower-docker:latest
   environment:
     - AMQP_USERNAME=rabbit_user
     - AMQP_PASSWORD=rabbit_password
     - AMQP_ADMIN_USERNAME=rabbit_user
     - AMQP_ADMIN_PASSWORD=rabbit_password
     - AMQP_HOST=broker-rabbitmq
     - AMQP_PORT=5672
     - AMQP_ADMIN_HOST=broker-rabbitmq
     - AMQP_ADMIN_PORT=15672
     - FLOWER_BASIC_AUTH=user:test
   ports:
     - "5555:5555"
   depends_on:
     - broker-rabbitmq
