# service type loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: flaskapi-svc
  namespace: flaskapi-ns
spec:
  selector:
    app: flaskapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer