apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: db-postgres
  name: db-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-postgres
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: db-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: db_password
            - name: POSTGRES_USER
              value: db_user
          image: postgres:11.2
          name: db-postgres
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
